// packages/react/src/components/NumericKeyboard.tsx
import type { KeyEvent } from '../types'
import React from 'react'
import keyboardBackspace from '../assets/icons/keyboard-backspace.svg'
import keyboardReturn from '../assets/icons/keyboard-return.svg'
import keyboardSpace from '../assets/icons/keyboard-space.svg'
import '../styles/NumericKeyboard.scss'

interface NumericKeyboardProps {
  onKey: (payload: KeyEvent) => void
  onExit: () => void
  keyboardRows?: string[][]
}

const DEFAULT_KEYBOARD_ROWS = [
  ['1', '2', '3'],
  ['4', '5', '6'],
  ['7', '8', '9'],
  ['back', '0', 'space'],
]

const NumericKeyboard: React.FC<NumericKeyboardProps> = ({
  onKey,
  onExit,
  keyboardRows = DEFAULT_KEYBOARD_ROWS,
}) => {
  const functionKeys = [
    { key: 'delete', icon: keyboardBackspace, text: '', alt: 'Delete' },
    { key: '.', icon: '', text: '.', alt: '.' },
    { key: '@', icon: '', text: '@', alt: '@' },
    { key: 'enter', icon: keyboardReturn, text: '', alt: 'Enter' },
  ]

  function handleKeyPress(key: string) {
    onKey({ key })
  }

  function handleSpecialKey(key: string, isControl = true) {
    onKey({ key, isControl })
  }

  function goBack() {
    onExit()
  }

  return (
    <div className="num-keyboard">
      <div className="num-keyboard__container">
        <div className="num-keyboard__left">
          <div className="num-keyboard__rows">
            {keyboardRows.map(row => (
              <div key={`row-${row.join('')}`} className="num-keyboard__row">
                {row.map(key => (
                  <button
                    key={`key-${row.join('')}-${key}`}
                    className={`num-keyboard__key ${
                      key === 'back' ? 'num-keyboard__key--back' : ''
                    } ${
                      key === 'space' ? 'num-keyboard__key--space' : ''
                    }`}
                    onClick={() =>
                      key === 'back'
                        ? goBack()
                        : key === 'space'
                          ? handleKeyPress(' ')
                          : handleKeyPress(key)}
                  >
                    {key === 'back'
                      ? (
                          '返回'
                        )
                      : key === 'space'
                        ? (
                            <img src={keyboardSpace} className="zhk-base__key-icon" alt="Space" />
                          )
                        : (
                            key
                          )}
                  </button>
                ))}
              </div>
            ))}
          </div>
        </div>

        <div className="num-keyboard__right">
          {functionKeys.map(fKey => (
            <button
              key={`func-${fKey.key}`}
              className="num-keyboard__key num-keyboard__key--function"
              onClick={() =>
                fKey.key === '.' || fKey.key === '@'
                  ? handleKeyPress(fKey.key)
                  : handleSpecialKey(fKey.key)}
            >
              {fKey.icon
                ? (
                    <img src={fKey.icon} className="num-keyboard__key-icon" alt={fKey.alt} />
                  )
                : (
                    <span>{fKey.text}</span>
                  )}
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}

export default NumericKeyboard

// packages/vue/src/components/NumericKeyboard.vue
<script setup lang="ts">
import type { KeyEvent } from '../types'
import backspaceIcon from '../assets/icons/keyboard-backspace.svg'
import returnIcon from '../assets/icons/keyboard-return.svg'
import '../styles/NumericKeyboard.scss'

withDefaults(defineProps<{
  keyboardRows?: string[][]
}>(), {
  keyboardRows: () => [
    ['1', '2', '3'],
    ['4', '5', '6'],
    ['7', '8', '9'],
    ['back', '0', 'space'],
  ],
})

const emit = defineEmits<{
  (e: 'key', payload: KeyEvent): void
  (e: 'exit'): void
}>()

const functionKeys = [
  { key: 'delete', icon: backspaceIcon, text: '', alt: 'Delete' },
  { key: '.', icon: '', text: '.', alt: '.' },
  { key: '@', icon: '', text: '@', alt: '@' },
  { key: 'enter', icon: returnIcon, text: '', alt: 'Enter' },
]

function handleKeyPress(key: string) {
  emit('key', { key })
}

function handleSpecialKey(key: string, isControl = true) {
  emit('key', { key, isControl })
}

function goBack() {
  emit('exit')
}
</script>

<template>
  <div class="num-keyboard">
    <div class="num-keyboard__container">
      <div class="num-keyboard__left">
        <div class="num-keyboard__rows">
          <div v-for="(row, rowIndex) in keyboardRows" :key="`row-${rowIndex}`" class="num-keyboard__row">
            <button
              v-for="(key, keyIndex) in row"
              :key="`key-${rowIndex}-${keyIndex}`"
              class="num-keyboard__key"
              :class="{
                'num-keyboard__key--back': key === 'back',
                'num-keyboard__key--space': key === 'space',
              }"
              @click="key === 'back' ? goBack() : (key === 'space' ? handleKeyPress(' ') : handleKeyPress(key))"
            >
              <template v-if="key === 'back'">
                返回
              </template>
              <template v-else-if="key === 'space'">
                <img src="../assets/icons/keyboard-space.svg" class="zhk-base__key-icon" alt="Space" />
              </template>
              <template v-else>
                {{ key }}
              </template>
            </button>
          </div>
        </div>
      </div>

      <div class="num-keyboard__right">
        <button
          v-for="(fKey, index) in functionKeys"
          :key="`func-${index}`"
          class="num-keyboard__key num-keyboard__key--function"
          @click="fKey.key === '.' || fKey.key === '@' ? handleKeyPress(fKey.key) : handleSpecialKey(fKey.key)"
        >
          <img v-if="fKey.icon" :src="fKey.icon" class="num-keyboard__key-icon" :alt="fKey.alt" />
          <span v-else>{{ fKey.text }}</span>
        </button>
      </div>
    </div>
  </div>
</template>
