// packages/react/src/components/ZhKeyboard.tsx
import type { KeyboardPosition } from '@zh-keyboard/core'
import type { KeyBoardMode, KeyEvent } from '../types'
import { useActiveElement, useElementSize, useEventListener } from '@reactuses/core'
import { calculateKeyboardPosition, delToInputElement, isInputElement, writeToInputElement } from '@zh-keyboard/core'
import classNames from 'classnames'
import React, { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import ReactDOM from 'react-dom'
import { useHandwritingRecognizer } from '../utils/useHandwritingRecognizer'
import HandwritingInput from './HandwritingInput'
import KeyboardBase from './KeyboardBase'
import NumericKeyboard from './NumericKeyboard'
import SymbolKeyboard from './SymbolKeyboard'
import '../styles/ZhKeyboard.scss'

interface ZhKeyboardProps {
  defaultMode?: KeyBoardMode
  enableHandwriting?: boolean
  position?: 'static' | 'float' | 'bottom'
  disableWhenNoFocus?: boolean
  onKey?: (payload: KeyEvent) => void
  className?: string
  style?: React.CSSProperties
  numKeys?: string[][]
}

const ZHKeyboardContent: React.FC<ZhKeyboardProps> = ({
  defaultMode = 'en',
  enableHandwriting = false,
  position = 'static',
  disableWhenNoFocus = true,
  onKey,
  className,
  style,
  numKeys,
}) => {
  const [mode, setMode] = useState<KeyBoardMode>(defaultMode)
  const previousModeRef = useRef<KeyBoardMode>(defaultMode)
  const [keyboardPosition, setKeyboardPosition] = useState<KeyboardPosition | null>(null)
  const keyboardRef = useRef<HTMLDivElement>(null)
  const activeElement = useActiveElement<HTMLInputElement>()

  const [_, keyboardHeight] = useElementSize(keyboardRef)

  const { recognizerInitialized, recognizerProgress } = useHandwritingRecognizer(enableHandwriting)

  useEffect(() => {
    // 仅在基础输入模式下更新 previousModeRef，以便 goBack 正确返回
    if (mode === 'en' || mode === 'zh') {
      previousModeRef.current = mode
    }
  }, [mode])

  const [isPositioned, setIsPositioned] = useState(false)
  const prevActiveElementRef = useRef<HTMLInputElement | null>(null)

  // 位置更新函数
  const updatePosition = useCallback(() => {
    if (!keyboardHeight)
      return

    const newPosition = calculateKeyboardPosition(
      activeElement,
      keyboardRef.current,
      position,
    )
    setKeyboardPosition(newPosition)
  }, [activeElement, position, keyboardHeight])

  const showKeyboard = useMemo(() => {
    return position === 'static' || isInputElement(activeElement)
  }, [activeElement, position])

  // 当showKeyboard或activeElement变化时更新位置
  useLayoutEffect(() => {
    // 检查activeElement是否真的变化了
    const activeElementChanged = prevActiveElementRef.current !== activeElement

    if (showKeyboard && keyboardHeight && activeElementChanged) {
      prevActiveElementRef.current = activeElement
      updatePosition()
    }
  }, [showKeyboard, activeElement, updatePosition, keyboardHeight])

  // 键盘首次挂载时的初始化
  useLayoutEffect(() => {
    if (keyboardHeight && !isPositioned) {
      updatePosition()
      const timer = setTimeout(() => {
        setIsPositioned(true)
      }, 0)
      return () => clearTimeout(timer)
    }
  }, [keyboardHeight, isPositioned, updatePosition])

  useLayoutEffect(() => {
    if (activeElement && isInputElement(activeElement)) {
      const inputmode = activeElement.dataset.inputmode as KeyBoardMode | undefined
      setMode((prevMode) => {
        return inputmode || prevMode
      })
    }
  }, [activeElement])

  const isKeyboardDisabled = useMemo(() => {
    if (disableWhenNoFocus === false)
      return false
    return !isInputElement(activeElement)
  }, [disableWhenNoFocus, activeElement])

  // 使用防抖来处理scroll和resize事件，避免频繁更新
  const debouncedUpdatePosition = useMemo(() => {
    let timer: ReturnType<typeof setTimeout>
    return () => {
      clearTimeout(timer)
      timer = setTimeout(updatePosition, 100)
    }
  }, [updatePosition])

  useEventListener('scroll', debouncedUpdatePosition, window, { passive: true })
  useEventListener('resize', debouncedUpdatePosition, window, { passive: true })

  const handleKeyEvent = useCallback((payload: KeyEvent) => {
    if (payload.isControl) {
      switch (payload.key) {
        case 'delete':
          if (isInputElement(activeElement))
            delToInputElement(activeElement)
          break
        default:
          break
      }
    } else {
      if (activeElement && isInputElement(activeElement))
        writeToInputElement(activeElement, payload.key)
    }
    if (onKey) {
      onKey(payload)
    }
  }, [onKey, activeElement])

  const goBack = useCallback(() => {
    setMode(previousModeRef.current)
  }, [])

  return (
    <div
      ref={keyboardRef}
      className={classNames('zhk', {
        'zhk--floating': position === 'float',
        'zhk--bottom': position === 'bottom',
        'zhk--disabled': isKeyboardDisabled,
      }, className)}
      style={{
        '--keyboard-height': `${keyboardHeight}px`,
        ...keyboardPosition,
        ...style,
        'display': !showKeyboard ? 'none' : undefined,
        'opacity': isPositioned ? 1 : 0,
      } as React.CSSProperties}
      onMouseDown={e => e.preventDefault()}
    >
      {isKeyboardDisabled || !showKeyboard || !keyboardHeight
        ? (
            <div className={classNames('zhk__disabled-overlay')}>
              <span>请选择输入框以启用键盘</span>
            </div>
          )
        : (
            <>
              {mode === 'hand' && (
                <HandwritingInput
                  recognizerInitialized={recognizerInitialized}
                  recognizerProgress={recognizerProgress}
                  onKey={handleKeyEvent}
                  onExit={goBack}
                />
              )}
              {mode === 'num' && (
                <NumericKeyboard
                  onKey={handleKeyEvent}
                  onExit={goBack}
                  keyboardRows={numKeys}
                />
              )}
              {mode === 'symbol' && <SymbolKeyboard onKey={handleKeyEvent} onExit={goBack} />}
              {(mode === 'en' || mode === 'zh') && (
                <KeyboardBase
                  mode={mode}
                  setMode={setMode}
                  enableHandwriting={enableHandwriting}
                  onKey={handleKeyEvent}
                />
              )}
            </>
          )}
    </div>
  )
}

const ZhKeyboard: React.FC<ZhKeyboardProps> = (props) => {
  const { position = 'static' } = props

  const keyboardContent = <ZHKeyboardContent {...props} />
  return position === 'static' ? keyboardContent : ReactDOM.createPortal(keyboardContent, document.body)
}

export default ZhKeyboard

// packages/vue/src/components/ZhKeyboard.vue
<script setup lang="ts">
import type { KeyboardPosition } from '@zh-keyboard/core'
import type { KeyBoardMode, KeyEvent } from '../types'
import { useActiveElement, useDebounceFn, useElementSize, useEventListener } from '@vueuse/core'
import { calculateKeyboardPosition, delToInputElement, isInputElement, writeToInputElement } from '@zh-keyboard/core'
import { computed, nextTick, ref, watch, watchEffect } from 'vue'
import { useHandwritingRecognizer } from '../utils/useHandwritingRecognizer'
import HandwritingInput from './HandwritingInput.vue'
import KeyboardBase from './KeyboardBase.vue'
import NumericKeyboard from './NumericKeyboard.vue'
import SymbolKeyboard from './SymbolKeyboard.vue'
import '../styles/ZhKeyboard.scss'

const props = withDefaults(defineProps<{
  /**
   * 默认的键盘模式
   */
  defaultMode?: KeyBoardMode
  /**
   * 是否启用手写输入
   */
  enableHandwriting?: boolean
  /**
   * 键盘定位模式
   * @default 'static'
   */
  position?: 'static' | 'float' | 'bottom'
  /**
   * 当没有input获得焦点时是否禁用键盘
   * @default true
   */
  disableWhenNoFocus?: boolean
  /**
   * 数字键盘的行配置
   */
  numKeys?: string[][]
}>(), {
  defaultMode: 'en',
  enableHandwriting: false,
  position: 'static',
  disableWhenNoFocus: true,
})

const emit = defineEmits<{
  (e: 'key', payload: KeyEvent): void
}>()

const mode = ref<KeyBoardMode>(props.defaultMode || 'en')
const previousMode = ref<KeyBoardMode>(props.defaultMode || 'en')

const candidates = ref<string[]>([])
const isSelectionOpen = ref(false)
const keyboardPosition = ref<KeyboardPosition | null>(null)
const keyboardRef = ref<HTMLElement | null>(null)

const { recognizerInitialized, recognizerProgress } = useHandwritingRecognizer(props.enableHandwriting)

// 监听mode变化，保存上一次的值
watch(mode, (newMode, oldMode) => {
  if (newMode !== oldMode) {
    previousMode.value = oldMode
  }
})

const activeElement = useActiveElement<HTMLInputElement>()

const inputElement = computed(() => {
  if (activeElement.value && isInputElement(activeElement.value)) {
    return activeElement.value
  }
  return null
})

const showKeyboard = computed(() => {
  return props.position === 'static' || !!(activeElement.value && isInputElement(activeElement.value))
})

const { height: keyboardHeight } = useElementSize(keyboardRef)
const isKeyboardInitialized = ref(false)

// 监听 inputElement 的变化
watchEffect(() => {
  if (inputElement.value) {
    const inputmode = inputElement.value.dataset.inputmode as KeyBoardMode | undefined
    if (inputmode) {
      mode.value = inputmode
    }
  }
})

// 只在键盘首次显示或输入框变化时更新位置，避免因高度变化导致的无限循环
watch([showKeyboard, inputElement], () => {
  if (showKeyboard.value && keyboardHeight.value) {
    nextTick(() => {
      updateKeyboardPosition()
      isKeyboardInitialized.value = true
    })
  }
})

// 键盘首次初始化时更新位置
watch(keyboardHeight, (newHeight, oldHeight) => {
  if (!isKeyboardInitialized.value && newHeight && newHeight !== oldHeight) {
    nextTick(() => {
      updateKeyboardPosition()
    })
  }
}, { once: true })

// 判断键盘是否被禁用（当前没有可输入的元素时禁用）
const isKeyboardDisabled = computed(() => {
  if (props.disableWhenNoFocus === false)
    return false

  return !inputElement.value
})

// 计算键盘位置
function updateKeyboardPosition() {
  if (!keyboardHeight.value)
    return
  const newPosition = calculateKeyboardPosition(
    inputElement.value,
    keyboardRef.value,
    props.position,
  )
  keyboardPosition.value = newPosition
}

// 页面滚动或窗口大小变化时更新键盘位置（添加防抖以避免频繁触发）
const debouncedUpdatePosition = useDebounceFn(updateKeyboardPosition, 100)
useEventListener(window, 'scroll', debouncedUpdatePosition, { passive: true })
useEventListener(window, 'resize', debouncedUpdatePosition, { passive: true })

function handleKeyEvent(payload: KeyEvent) {
  if (payload.isControl) {
    switch (payload.key) {
      case 'delete':
        delToInputElement(inputElement.value!)
        break
      case 'more':
        isSelectionOpen.value = true
        break
      default:
        break
    }
    return
  } else {
    inputText(payload.key)
  }
  emit('key', payload)
}

function inputText(text: string) {
  writeToInputElement(inputElement.value!, text)
}

function goBack() {
  mode.value = previousMode.value
}

function handleRecognize(results: string[]) {
  candidates.value = results
}
</script>

<template>
  <Teleport to="body" :disabled="position === 'static'">
    <div
      v-show="showKeyboard"
      v-bind="$attrs"
      ref="keyboardRef"
      class="zhk"
      :class="{
        'zhk--floating': position === 'float',
        'zhk--bottom': position === 'bottom',
        'zhk--disabled': isKeyboardDisabled,
      }"
      :style="{
        '--keyboard-height': `${keyboardHeight}px`,
        ...keyboardPosition,
      }"
      @mousedown.prevent
    >
      <div v-if="isKeyboardDisabled || !showKeyboard || !keyboardHeight" class="zhk__disabled-overlay">
        <span>请选择输入框以启用键盘</span>
      </div>
      <template v-else>
        <HandwritingInput
          v-if="mode === 'hand'"
          :recognizer-initialized
          :recognizer-progress
          @key="handleKeyEvent"
          @exit="goBack"
          @recognize="handleRecognize"
        />
        <NumericKeyboard
          v-else-if="mode === 'num'"
          :keyboard-rows="numKeys"
          @key="handleKeyEvent"
          @exit="goBack"
        />
        <SymbolKeyboard
          v-else-if="mode === 'symbol'"
          @key="handleKeyEvent"
          @exit="goBack"
        />
        <KeyboardBase
          v-else-if="mode === 'en' || mode === 'zh'"
          v-model="mode"
          :enable-handwriting="enableHandwriting"
          @key="handleKeyEvent"
        />
      </template>
    </div>
  </Teleport>
</template>
